### ISSUE TITLE
Support PlotlyBase

### ISSUE THREAD

**Issue by cstjean** [waralex/Dashboards#1]
Hi, that's a fantastic package, thank you! Would it make sense to support the PlotlyBase interface? We have lots of Plotly code + Interact, which would be much nicer as a unified dash application, but porting it would take time. Supporting PlotlyBase would make it easier.

**Comment by waralex** [comment]
Hi
I think it’s possible, but I need to take a closer look at PlotlyBase

**Comment by waralex** [comment]
Look at this [example](https://github.com/waralex/DashboardsExamples/blob/master/examples/plotly_base.jl) 
Is that what you need?

**Comment by cstjean** [comment]
I think so! I won't have time to look at it over the week-end, but maybe on Monday.

**Comment by waralex** [comment]
@cstjean I added support of the PlotlyBase interface to master. Look at [Plot usage in layout](https://github.com/waralex/DashboardsExamples/blob/master/dash_tutorial/2_dash_layout_4.jl), [Plot usage in callback](https://github.com/waralex/DashboardsExamples/blob/master/dash_tutorial/3_basic_dash_callbacks_2.jl)
