### ISSUE TITLE
Check install instructions...

### ISSUE THREAD

**Issue by KajWiik** [waralex/Dashboards#2]
```
julia> import Pkg; Pkg.add("https://github.com/waralex/Dashboards.git")
ERROR: https://github.com/waralex/Dashboards.git is not a valid packagename.
The argument appears to be a URL or path, perhaps you meant `Pkg.add(PackageSpec(url="..."))` or `Pkg.add(PackageSpec(path="..."))`.
Stacktrace:
 [1] pkgerror(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/Types.jl:112
 [2] check_package_name(::String, ::Symbol) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:28
 [3] iterate at ./none:0 [inlined]
 [4] collect(::Base.Generator{Array{String,1},getfield(Pkg.API, Symbol("##22#23"))}) at ./array.jl:606
 [5] #add#21 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:65 [inlined]
 [6] add at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:65 [inlined]
 [7] #add#20(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.add), ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:64
 [8] add(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:64
 [9] top-level scope at REPL[1]:1
```
but 

```
(v1.2) pkg> add https://github.com/waralex/Dashboards
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `https://github.com/waralex/Dashboards`
  Updating git-repo `https://github.com/waralex/Dashboards`
  Updating git-repo `https://github.com/waralex/Dashboards`
 Resolving package versions...
 Installed Compat ───────── v2.2.0
 Installed CSTParser ────── v1.0.0
 Installed BinaryProvider ─ v0.5.7
 Installed DataStructures ─ v0.17.5
 Installed MbedTLS ──────── v0.7.0
  Updating `~/.julia/environments/v1.2/Project.toml`
  [9024f26f] + Dashboards v0.1.0 #master (https://github.com/waralex/Dashboards)
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [b99e7846] ↑ BinaryProvider v0.5.6 ⇒ v0.5.7
  [00ebfdb7] + CSTParser v1.0.0
  [34da2185] ↑ Compat v2.1.0 ⇒ v2.2.0
  [9024f26f] + Dashboards v0.1.0 #master (https://github.com/waralex/Dashboards)
  [864edb3b] + DataStructures v0.17.5
  [cd3eb016] + HTTP v0.8.6
  [83e8ac13] + IniFile v0.5.0
  [2535ab7d] + JSON2 v0.3.1
  [1914dd2f] + MacroTools v0.5.1
  [739be429] + MbedTLS v0.7.0
  [bac558e1] + OrderedCollections v1.1.0
  [0796e94c] + Tokenize v0.5.6
  Building MbedTLS ───→ `~/.julia/packages/MbedTLS/a1JFn/deps/build.log`
  Building Dashboards → `~/.julia/packages/Dashboards/noLTU/deps/build.log`
```
works OK (though with only v1.2).

**Comment by waralex** [comment]
I changed install instruction and added information about the required Julia version. I'm new to Julia and I wrote this package for the actual version 1.2
If it is critical I'll try to make it compatible with 1.0.5 LTS.

**Comment by KajWiik** [comment]
Many thanks, works beautifully! For me (and most of the users, I guess) dependency of >1.2 is OK but it is good to mention it in the docs..

**Comment by EricForgy** [comment]
This is great! Welcome to Julia @waralex 😊 

I'm guessing you can support Julia v0.7 to v1.2 if you don't commit the Manifest. I had a similar issue with Pages.jl recently.

Edit: To elaborate a little, HTTP.jl has a dependency on MbedTLS.jl

https://github.com/JuliaWeb/HTTP.jl/blob/master/Project.toml#L14

It has there

```toml
[compat]
MbedTLS = "0.6.8, 0.7"
```

Version v0.7 of MbedTLS only works on Julia v1.2, so if you create your Manifest.toml using Julia v1.2, it will put MbedTLS v0.7 in you Manifest.toml. You can see that here:

https://github.com/waralex/Dashboards/blob/master/Manifest.toml#L97

Now, if you check this Manifest.toml into GitHub, the CI will use it, which means it will fail on Julia versions earlier than v1.2.

However, if you remove your Manifest.toml, I suspect (> 90% certain) it will work on other versions of Julia as well.

Hope this helps (I may submit a PR for this).

Edit^2: #3

**Comment by waralex** [comment]
Thanks!
> However, if you remove your Manifest.toml, I suspect (> 90% certain) it will work on other versions of Julia as well.

I use, for example, the `isnothing()` function, which appeared in version 1.1 so without changing the code, it will not work in earlier versions.

**Comment by EricForgy** [comment]
I see. Well, v1.1 and v1.2 is still better than v1.2 :)

**Comment by waralex** [comment]
@EricForgy I merged your request and added information what it works with 1.1 to README.
Thanks!

**Comment by EricForgy** [comment]
Excellent 👍😊

PS: I wrote Figures.jl (that also uses plotly.js) out of similar frustrations that led you to write this package :)

**Comment by waralex** [comment]
@EricForgy It seems to me that this is an obvious idea to use Dash frontend. I was surprised that it was not implemented before. 
Another idea is what we need the server application for maintaining a set of dashboards with a suitable workflow to add/update a dashboard. Plotly Dash has such server in the enterprise edition.
As I understand the [gallery page](https://dash-gallery.plotly.host/Portal/) is just an example of this server

**Comment by EricForgy** [comment]
> @EricForgy It seems to me that this is an obvious idea to use Dash frontend. I was surprised that it was not implemented before.

I agree. There has been a bit of talking here and there, but there are not a lot of people working on web stuff with Julia at the moment (from what I can tell), which is a shame as I think Julia would be good for this stuff. The people who are doing web stuff tend to be short of time and resources. Dashboards is a great idea and I'm glad you came around and did it :)

> Another idea is what we need the server application for maintaining a set of dashboards with a suitable workflow to add/update a dashboard. Plotly Dash has such server in the enterprise edition.

I'm not a web expert by a long shot, but the main purpose of Pages.jl was to provide a simple server for these types of applications. We also have Genie.jl and Mux.jl that could be suitable. I'm definitely interested in hearing your thoughts.
