### ISSUE TITLE
Docs look wrong

### ISSUE THREAD

**Issue by PallHaraldsson** [waralex/Dashboards#21]
I clicked edit on Github, from this link: https://waralex.github.io/Dashboards.jl/stable/

I found "layoutm​aker" to look odd, with m subscripted. I know the reason, or I guess "layout_m​aker"  taken as TeX? I'm not sure what the solution is, and for me that's ok, as I just use there.

With that out of the way, is there any reason to prefer https://github.com/plotly/Dash.jl (or similar Python package) to Dashboard.jl? I got the example to work for the latter, while getting an error for the former, and since I think <s>this package is the future</s>, I guess I'll stay with it, and see how it goes.

**Comment by waralex** [comment]
Hi.
https://github.com/plotly/Dash.jl  is a further development of this package. It is still unstable, but I am gradually bringing it to full compliance with other Plotly products with the help of the Plotly team. Dashboards will not be developed further.

**Comment by PallHaraldsson** [comment]
Thanks, I ran the example here, and it was ok, and I did "fix" the examples at Dash.jl, still got errors with both.

Would you say I should use this package rather than Dash.jl as it doesn't work? And it should be simple to migrate later? I'm completely new to Dash, would you say these Julia packages are close to what you would get in Python and just small hurdles to get to work? [I see in an issue at Dash.jl, that R has one more feature, and Python yet another one.]

I found this line in tests, and "fixed" by copy-pasing it (should it be used for examples, or html_div qualified? I was thinking of doing a PR):

```
export html_div, html_a, dcc_input, dcc_graph, html_h1, html_img
```

After fixing that way, the web server ran while I got a blank page because of the error below (and before the "fix" I got "ERROR: UndefVarError: html_div not defined"):

```
julia> run_server(app, "0.0.0.0", 8081)
[ Info: Running on http://0.0.0.0:8081

┌ Error: error handling request
│   exception =
│    IOError: stream is closed or unusable
│    Stacktrace:
│     [1] check_open at ./stream.jl:328 [inlined]
│     [2] uv_write_async(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:959
│     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:922
│     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:1005
│     [5] unsafe_write at /home/pharaldsson_sym/.julia/packages/HTTP/BOJmV/src/ConnectionPool.jl:174 [inlined]
│     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /home/pharaldsson_sym/.julia/packages/HTTP/BOJmV/src/Streams.jl:98
│     [7] unsafe_write at ./io.jl:622 [inlined]
│     [8] write at ./io.jl:645 [inlined]
│     [9] handle(::HTTP.Handlers.RequestHandlerFunction{Dash.var"#52#53"{Array{String,1},Int64,HTTP.Handlers.RequestHandlerFunction{Dash.var"#49#50"{Dash.Router,Dash.HandlerState}}}}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/pharaldsson_sym/.julia/packages/HTTP/BOJmV/src/Handlers.jl:279
│     [10] #4 at /home/pharaldsson_sym/.julia/packages/HTTP/BOJmV/src/Handlers.jl:345 [inlined]
│     [11] macro expansion at /home/pharaldsson_sym/.julia/packages/HTTP/BOJmV/src/Servers.jl:367 [inlined]
│     [12] (::HTTP.Servers.var"#13#14"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.RequestHandlerFunction{Dash.var"#52#53"{Array{String,1},Int64,HTTP.Handlers.RequestHandlerFunction{Dash.var"#49#50"{Dash.Router,Dash.HandlerState}}}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:356
└ @ HTTP.Servers ~/.julia/packages/HTTP/BOJmV/src/Servers.jl:373
^Cfinished
```

**Comment by waralex** [comment]
Can I see the full code of the example you are trying to run?

**Comment by PallHaraldsson** [comment]
It's just there https://github.com/plotly/Dash.jl under "Basic application".

I actually see with "View source" that the code gets to the browser, and I saw "Loading" blinking, then blank page.
